### ISSUE TITLE
After using it, it is still prompted to purchase

### ISSUE THREAD

**Issue by TjXySky** [wangzhenjjcn/AdobeGenp#14]
On July 15, 2024, I downloaded Adobe Creative Cloud from the official website and used Adobe GenP, but the result was still prompted to buy or try
![AdobeGenP1](https://github.com/user-attachments/assets/fd89d9df-6860-4fe7-a5ee-907976858592)
![AdobeGenP2](https://github.com/user-attachments/assets/4a217d30-f329-43be-84db-30b732826f95)

**Comment by TjXySky** [comment]
Probably an issue with my windows version, I thought this version worked fine, so I installed this version

**Comment by wangzhenjjcn** [comment]
After path,logout account,if it's still not work,Please purchase a genuine Adobe license !

**Comment by wangzhenjjcn** [comment]
befor path logout account in cc

**Comment by TjXySky** [comment]
Thanks, I reinstalled the latest system, probably because the system version is too old
