### ISSUE TITLE
THIS APP WILL DISABLE IN 5 DAYS

### ISSUE THREAD

**Issue by setube** [wangzhenjjcn/AdobeGenp#15]
This unlicensed Adobe app is not genuine 和 will be disabled soon Adobe offers you a 5-day grace period to switch to a genuine Adobe app — at a discount — 和 uninstall unlicensed Adobe apps. 

![Clip_2024-07-17_08-48-43](https://github.com/user-attachments/assets/7c12c504-0fec-4226-badf-d38f26576961)

[Copy.log](https://github.com/user-attachments/files/16257855/Copy.log)

**Comment by wangzhenjjcn** [comment]
After path,logout account,if it's still not worAfter path,logout account,if it's still not work,befor path logout account in cc,Please purchase a genuine Adobe license !k,befor path logout account in cc,Please purchase a genuine Adobe license !
