### ISSUE TITLE
Open software flashback after cracking Photoshop 25.11

### ISSUE THREAD

**Issue by mwx280** [wangzhenjjcn/AdobeGenp#17]
After updating Adobe Photoshop 25.11 today and using AdobeGenP Harmony Photoshop, Photoshop is flashing. Uninstalling and reinstalling does the same thing, how do I fix this?

Environment: Windows 11 Professional

**Comment by mwx280** [comment]
I've confirmed that I don't have the Adobe Genuine Validator installed.

**Comment by lfdisk** [comment]
Log off from Adobe Creative Cloud。
在 Adobe Creative Cloud 中退出登录。

**Comment by mwx280** [comment]
> Log off from Adobe Creative Cloud。 在 Adobe Creative Cloud 中退出登录。
This method can fix the crash issue, but not completely, Photoshop does not show the welcome screen after opening

**Comment by mwx280** [comment]
> Log off from Adobe Creative Cloud。 在 Adobe Creative Cloud 中退出登录。

This method can fix the crash issue, but not completely, Photoshop does not show the welcome screen after opening

**Comment by SajunaOo** [comment]
复现出了该问题

**Comment by Sco-ohhG** [comment]
This method can fix the crash issue, but not completely, Photoshop does not show the welcome screen after opening
+1

**Comment by wangzhenjjcn** [comment]
@mwx280  logout account in adobe cc (critive cloud) then re-path, it should be work

**Comment by wangzhenjjcn** [comment]
@Sco-ohhG  works is good
