### ISSUE TITLE
Photoshop(25.11)Version    Can't use it, still need to subscribe

### ISSUE THREAD

**Issue by whb8019** [wangzhenjjcn/AdobeGenp#19]
Photoshop(25.11)Version    Can't use it, still need to subscribe

**Comment by Fujiwara-Saki** [comment]
yes

**Comment by Aunft** [comment]
> Photoshop（25.11）版本无法使用，仍需订阅

你是仍可以打开窗口吗？我在打开的一瞬间就突然关闭了（只有一次正常进入与使用）

**Comment by wangzhenjjcn** [comment]
no need to edit any file mamuly
1.login account in adobe cc
2.try what apps you want to and download with install automate
3.finally logout account in adobe cc
4.it should be fine after you path it
