### ISSUE TITLE
Adobe banned any download without subscribe

### ISSUE THREAD

**Issue by soldiereleven** [wangzhenjjcn/AdobeGenp#20]
Now in adobe creative cloud, if you didn't pay for a certain software, you can not download it at all. I also can not find a download link in the official website. Is there any solutions?

**Comment by wangzhenjjcn** [comment]
first:install adobe cc 
then:try what app you want to install
finally:logout and path it ,it should be fine


no need to edit any file mamuly
1.login account in adobe cc
2.try what apps you want to and download with install automate
3.finally logout account in adobe cc
4.it should be fine after you path it
