### ISSUE TITLE
AdobeGenP-3.4.14.1 cannot search Adobe Creative Cloud files

### ISSUE THREAD

**Issue by whb8019** [wangzhenjjcn/AdobeGenp#22]
AdobeGenP-3.4.14.1 cannot search Adobe Creative Cloud files

**Comment by whb8019** [comment]
![Uploading 2024-08-14 220511.png…]()

**Comment by whb8019** [comment]
![jpeg](https://github.com/user-attachments/assets/b76363e1-dec4-48f3-931b-11686056cb6f)

**Comment by wangzhenjjcn** [comment]
as u can C , a btn named path cc
