### ISSUE TITLE
App Has ben disabled :(

### ISSUE THREAD

**Issue by megvadulthangya** [wangzhenjjcn/AdobeGenp#23]
Hello! What can i do if i see those windows?
I run search then patch all, but that popup still comes back... 

In the near future need to install newer version of w11... so... next time install then run AdobeGenp? before i get any popupthingy?

BTW this is ps 2017 installed from iso

![Screenshot 07-22-2024 19 08 58](https://github.com/user-attachments/assets/bd67ac26-748c-4544-99d1-31cd0cc5b218)
![Screenshot 08-22-2024 05 24 42](https://github.com/user-attachments/assets/c02eed7b-15b0-415b-9a15-931594cab33f)

**Comment by wangzhenjjcn** [comment]
dont install adobe genuine service when install cc
just install last version apps
no test on your old version app like 2017 and you should test by yourself
if it not works,reinstall windows can solute this problem


1.login account in adobe cc
2.try what apps you want to and download with install automate
3.finally logout account in adobe cc
4.it should be fine after you path it



in the end Please purchase a genuine Adobe license !
