### ISSUE TITLE
破解完后打开PS出现闪退现象

### ISSUE THREAD

**Issue by blacowboy** [wangzhenjjcn/AdobeGenp#24]
未破解时，打开PS后会打开购买界面，破解后打开直接闪退

**Comment by wangzhenjjcn** [comment]
How to use GenP:

If you want to patch all Adobe apps in default location:
Press ‘Search Files’ – wait until GenP finds all files.
Press ‘Pill Button’ – wait until GenP do it’s job.
One Adobe app at a time:
Press ‘Custom path’ – select folder that you want [depending upon the app you want to patch]
Press ‘Search Files’ – wait until GenP finds all files.
Press ‘Pill Button’ – wait until GenP do it’s job.

Install CC>Login>Try Apps>Logout CC>Path>It should be Work!
Please purchase a genuine Adobe license !

**Comment by wangzhenjjcn** [comment]
@blacowboy  install a pre version like v2024 instead of v2025
