### ISSUE TITLE
无法使用任何已破解程序！

### ISSUE THREAD

**Issue by Aunft** [wangzhenjjcn/AdobeGenp#25]
PR、AE、AU等软件24.6版本都出现了闪退情况，PS25.11破解窗口只出现一瞬间

**Comment by wangzhenjjcn** [comment]
How to use GenP:

If you want to patch all Adobe apps in default location:
Press ‘Search Files’ – wait until GenP finds all files.
Press ‘Pill Button’ – wait until GenP do it’s job.
One Adobe app at a time:
Press ‘Custom path’ – select folder that you want [depending upon the app you want to patch]
Press ‘Search Files’ – wait until GenP finds all files.
Press ‘Pill Button’ – wait until GenP do it’s job.

Install CC>Login>Try Apps>Logout CC>Path>It should be Work!
