### ISSUE TITLE
About Genp being detected by Windows Defender and deleted subsequently

### ISSUE THREAD

**Issue by NineNightMeow** [wangzhenjjcn/AdobeGenp#28]
When I unzip the Genp,the Windows Defender immediately have the Genp deleted,leaving with a screen arising with a message went 
'The operation could not be completed successfully because the file contained a virus or potentially junk software."
But it was not solved by having Windows Defender transitorily.Every time I have it unzipped,the Genp was going to be deleted right now.Adding the zip into the Exclusions seems to be fruitless as well.I wonder how I can use Genp,waiting for a method.(Ps:Could I can add the zip into an excluded folder to solve this?)

**Comment by vrijenaam** [comment]
Exclude the folder where you download the zip to. (eg; %user%/Downloads)
Exclude the folder where you extract to. (eg. that same downloads folder)
