### ISSUE TITLE
Source??

### ISSUE THREAD

**Issue by neilhuang007** [wangzhenjjcn/AdobeGenp#35]
If its community edition there should be a source

**Comment by neilhuang007** [comment]
its classified as a rat by basically any anticheat

**Comment by AsafCN** [comment]
> ###
> [Sep 29, 2024](#issuecomment-2381089656)

anticheat?
you know that anticheats is for games. you mean anti-viruses?

**Comment by neilhuang007** [comment]
Yea， autocorrect screwed me up, the open sourced version is not flagged, only the ones without sources are flagged by antivirus
