### ISSUE TITLE
After Effects windows file browser crashes

### ISSUE THREAD

**Issue by zhengjie-ng** [wangzhenjjcn/AdobeGenp#36]
When using anything that will launch windows file browser in after effects, it will crashes. 

File>Save as...
File>Import>Files

![Screenshot 2024-10-02 180234](https://github.com/user-attachments/assets/52c9309a-8fa5-4a55-9787-66759738980a)

**Comment by wangzhenjjcn** [comment]
@zhengjie-ng Your feedback has been recorded,Try a pre or earlier release instead.
