### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by mainulXD18** [wangzhenjjcn/AdobeGenp#39]
![image](https://github.com/user-attachments/assets/e1cdf615-8137-489d-b8c4-48110d438120)

The newest release is a virus?

**Comment by wangzhenjjcn** [comment]
@mainulXD18 Fish?

**Comment by mainulXD18** [comment]
what do you mean?

**Comment by wangzhenjjcn** [comment]
@mainulXD18 stop and close your antivirus programs and stop wndows definder service then download again
after download run as administrator choice more and still run it 

if you dont wanna do these , pls dont download it .
![image](https://github.com/user-attachments/assets/5c90eac6-cacd-42a3-aabf-b9b0f4738f7a)
![image](https://github.com/user-attachments/assets/849ed44b-e990-4f7d-a736-9957f4248663)
![image](https://github.com/user-attachments/assets/27d5655a-eb6c-43c1-a019-751b58fdf37f)
![image](https://github.com/user-attachments/assets/2f458170-3ce9-4819-897f-449d537731d6)
