### ISSUE TITLE
acrocef.exe (Adobe AcroCEF) must be patched

### ISSUE THREAD

**Issue by hellomynameisnoone** [wangzhenjjcn/AdobeGenp#45]
AdobeGenp should include patching acrocef.exe (Adobe AcroCEF) for Adobe Acrobat Pro to avoid calling home and avoid the license issue

**Comment by hellomynameisnoone** [comment]
Akamai Technology should be blocked/removed, they implemented anti piracy measurements

some calls:
a1815.dscr.akamai.net
 a2-16-224-134.deploy.static.akamaitechnologies.com
 a2-16-54-173.deploy.static.akamaitechnologies.com
 a2-16-8-184.deploy.static.akamaitechnologies.com
 a23-14-136-168.deploy.static.akamaitechnologies.com
 a23-14-137-23.deploy.static.akamaitechnologies.com
 a23-41-116-170.deploy.static.akamaitechnologies.com
 a92-123-56-132.deploy.static.akamaitechnologies.com
 adobeid-na1.services.adobe.com.cdn.cloudflare.net
 auth.services.adobe.com.cdn.cloudflare.net
 cc-api-data.adobe.io
 crs.cr.adobe.com
 delegated.adobelogin.com
 e4578.dscg.akamaiedge.net
 e7808.dscg.akamaiedge.net
 ec2-107-22-247-231.compute-1.amazonaws.com
 ec2-23-22-254-206.compute-1.amazonaws.com
 ec2-54-227-187-23.compute-1.amazonaws.com
 g2a02-26f0-00e0-0491-0000-0000-0000-11e2.deploy.static.akamaitechnologies.com
 g2a02-26f0-00e0-04bc-0000-0000-0000-11e2.deploy.static.akamaitechnologies.com
 g2a02-26f0-0980-0008-0000-0000-0210-5859.deploy.static.akamaitechnologies.com
 g2a02-26f0-1380-0027-0000-0000-5f64-6d5d.deploy.static.akamaitechnologies.com
 g2a02-26f0-1380-0027-0000-0000-5f64-6d61.deploy.static.akamaitechnologies.com
 g2a02-26f0-1380-0192-0000-0000-0000-11e2.deploy.static.akamaitechnologies.com
 g2a02-26f0-2380-0003-0000-0000-0212-bc95.deploy.static.akamaitechnologies.com
 ic.adobe.io
 ip-63-140-62-17.data.adobedc.net
 ip-63-140-62-222.data.adobedc.net
 ip-63-140-62-27.data.adobedc.net
 lcs-cops.adobe.io
 o1383653.ingest.sentry.io

**Comment by hellomynameisnoone** [comment]
2001:4860:4860::8888	 
2001:4860:4860::8844	 
162.159.61.3	 chrome.cloudflare-dns.com
2a06:98c1:52::3	 
54.227.187.23	 ic.adobe.io
2.16.8.184	 
2a02:26f0:2380:3::212:bc95	 
2a02:26f0:e0:4bc::11e2	 
172.64.155.179	 auth.services.adobe.com.cdn.cloudflare.net
172.64.155.61	 adobeid-na1.services.adobe.com.cdn.cloudflare.net
23.14.137.23	 
23.14.136.168	 
63.140.62.27	 
2.16.224.134	 
63.140.62.222	 sstats.adobe.com
107.22.247.231	 
54.144.73.197	 ic.adobe.io
2a02:26f0:1380:27::5f64:6d61	 
2a02:26f0:e0:491::11e2	 
104.18.32.195	 adobeid-na1.services.adobe.com.cdn.cloudflare.net
63.140.62.17	 
23.22.254.206	 
2a02:26f0:1380:27::5f64:6d5d	 
8.8.4.4	 dns.google
172.64.41.3	 chrome.cloudflare-dns.com
18.207.85.246	 ic.adobe.io
23.41.116.170	 
23.41.116.173	 e4578.dscg.akamaiedge.net
23.41.117.26	 e7808.dscg.akamaiedge.net
2.16.54.173	 
52.5.13.197	 ic.adobe.io
2a02:26f0:2380:3::212:bc93	 
2a02:26f0:e0:2bc::11a6	 
34.193.227.236	 
2a02:26f0:980:696::11a6	 
2a02:26f0:980:689::11a6	 
2a02:26f0:e0:4a8::1e80	 
2.16.54.171	 
52.202.204.11	 
96.16.86.9	 
2a02:26f0:980:5a4::11e2	 
2a02:26f0:980:e::210:581d

**Comment by wangzhenjjcn** [comment]
https://www.mediafire.com/file/7zg3tsq06t96ua5/AdobeAcrobatProDC2024.004.20243x64.exe/file

@hellomynameisnoone

**Comment by wangzhenjjcn** [comment]
@hellomynameisnoone download cracked installer in main branch
