### ISSUE TITLE
要在Adobe应用程序中访问Firefly支持的功能, 您必须拥有正版Adobe应用程序。

### ISSUE THREAD

**Issue by R6SD** [wangzhenjjcn/AdobeGenp#7]
![image](https://github.com/wangzhenjjcn/AdobeGenp/assets/94024616/0844a84e-2f4c-4337-a6d0-5c40747b0a35)

**Comment by SadEPa28** [comment]
me too!

**Comment by wangzhenjjcn** [comment]
try a older version to instead this beta version

**Comment by SadEPa28** [comment]
> try a older version to instead this beta version

@wangzhenjjcn 还是一样

**Comment by 1q2zb** [comment]
> > try a older version to instead this beta version
> 
> @wangzhenjjcn 还是一样

请问问题解决了吗？如果解决了，请问如何解决的。
