### ISSUE TITLE
Photoshop 2024破解之后无法使用

### ISSUE THREAD

**Issue by SadEPa28** [wangzhenjjcn/AdobeGenp#9]
破解Photoshop 2024后打开程序会出现
This non-genuine app willbe disabled soon.Contact your IT Administrator.
![image](https://github.com/wangzhenjjcn/AdobeGenp/assets/159880091/55d9a547-5b90-4eb8-87c9-4463916f4ca1)

**Comment by fsjoy52** [comment]
me too!

**Comment by SadEPa28** [comment]
@wangzhenjjcn

**Comment by Svmtimend** [comment]
+1

**Comment by wangzhenjjcn** [comment]
@fsjoy52 @SadEPa28 try a older version to instead this beta version
